<?php

use Illuminate\Database\Seeder;

class actionsSeederTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if(DB::table('actions')->get()->count() == 0){
            $actions = [
                [
                    'name_action' => 'Actions',
                    'link_action' => 'admin',
                    'is_public'   => '1',
                    'description' => 'Actions 1',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'All Actions',
                    'link_action' => 'admin/actions',
                    'is_public'   => '1',
                    'description' => 'Actions 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'Create Actions',
                    'link_action' => 'admin/actions/create',
                    'is_public'   => '1',
                    'description' => 'Actions 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],
                [
                    'name_action' => 'Comments',
                    'link_action' => 'admin',
                    'is_public'   => '1',
                    'description' => 'Comments 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'All Comments',
                    'link_action' => 'admin/comments',
                    'is_public'   => '1',
                    'description' => 'Comments 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],
                [
                    'name_action' => 'Companies',
                    'link_action' => 'admin',
                    'is_public'   => '1',
                    'description' => 'Companies 1',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'All Companies',
                    'link_action' => 'admin/companies',
                    'is_public'   => '1',
                    'description' => 'Companies 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'Create Companies',
                    'link_action' => 'admin/companies/create',
                    'is_public'   => '1',
                    'description' => 'Companies 3',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],
                [
                    'name_action' => 'Contacts',
                    'link_action' => 'admin',
                    'is_public'   => '1',
                    'description' => 'Contacts 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'All Contacts',
                    'link_action' => 'admin/contacts',
                    'is_public'   => '1',
                    'description' => 'Contacts 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'Events',
                    'link_action' => 'admin',
                    'is_public'   => '1',
                    'description' => 'Events 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'All Events',
                    'link_action' => 'admin/events',
                    'is_public'   => '1',
                    'description' => 'Events 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'Create Events',
                    'link_action' => 'admin/events/create',
                    'is_public'   => '1',
                    'description' => 'Events 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],
                [
                    'name_action' => 'Groups',
                    'link_action' => 'admin',
                    'is_public'   => '1',
                    'description' => 'Groups 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'All Groups',
                    'link_action' => 'admin/groups',
                    'is_public'   => '1',
                    'description' => 'Groups 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'Create Groups',
                    'link_action' => 'admin/groups/create',
                    'is_public'   => '1',
                    'description' => 'Groups 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],
                [
                    'name_action' => 'Menus',
                    'link_action' => 'admin',
                    'is_public'   => '1',
                    'description' => 'Menus 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'All Menus',
                    'link_action' => 'admin/menus',
                    'is_public'   => '1',
                    'description' => 'Menus 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'Create Menus',
                    'link_action' => 'admin/menus/create',
                    'is_public'   => '1',
                    'description' => 'Menus 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],
                [
                    'name_action' => 'Oders',
                    'link_action' => 'admin',
                    'is_public'   => '1',
                    'description' => 'Oders 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'All Oders',
                    'link_action' => 'admin/orders',
                    'is_public'   => '1',
                    'description' => 'Oders 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'Type Events',
                    'link_action' => 'admin',
                    'is_public'   => '1',
                    'description' => 'Type Events 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'All Type Events',
                    'link_action' => 'admin/type_events',
                    'is_public'   => '1',
                    'description' => 'Type Events 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'Create Type Events',
                    'link_action' => 'admin/type_events/create',
                    'is_public'   => '1',
                    'description' => 'Type Events 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'Users',
                    'link_action' => 'admin',
                    'is_public'   => '1',
                    'description' => 'Users 1',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'All Users',
                    'link_action' => 'admin/users',
                    'is_public'   => '1',
                    'description' => 'Users 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'Create Users',
                    'link_action' => 'admin/users/create',
                    'is_public'   => '1',
                    'description' => 'Users 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'Tickets',
                    'link_action' => 'admin',
                    'is_public'   => '1',
                    'description' => 'Tickets 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ],[
                    'name_action' => 'All Tickets',
                    'link_action' => 'admin/tickets',
                    'is_public'   => '1',
                    'description' => 'Tickets 2',
                    'is_delete'   => '0',
                    'created_at'  => DB::raw('now()'),
                    'updated_at'  => DB::raw('now()'),
                ]
            ];
            DB::table('actions')->insert($actions);
        }
    }
}
