<?php

use Illuminate\Database\Seeder;

class menusSeederTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (DB::table('menus')->get()->count() == 0) {
            $menus = [
                [
                    'name_menu'   => 'Actions',
                    'action_id'   => '1',
                    'url'         => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '0',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'All Actions',
                    'action_id'   => '2',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '1',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Create Actions',
                    'action_id'   => '3',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '1',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Comments',
                    'action_id'   => '4',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '0',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'All Comments',
                    'action_id'   => '5',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '4',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Companies',
                    'action_id'   => '6',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '0',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'All Companies',
                    'action_id'   => '7',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '6',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Create Companies',
                    'action_id'   => '8',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '6',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Contacts',
                    'action_id'   => '9',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '0',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'All Contacts',
                    'action_id'   => '10',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '9',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Events',
                    'action_id'   => '11',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '0',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'All Events',
                    'action_id'   => '12',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '11',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Create Events',
                    'action_id'   => '13',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '11',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Groups',
                    'action_id'   => '14',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '0',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'All Groups',
                    'action_id'   => '15',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '14',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Create Groups',
                    'action_id'   => '16',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '14',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Menus',
                    'action_id'   => '17',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '0',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'All Menus',
                    'action_id'   => '18',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '17',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Create Menus',
                    'action_id'   => '19',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '17',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Orders',
                    'action_id'   => '20',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '0',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Orders Not Payments',
                    'action_id'   => '21',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '20',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Type Events',
                    'action_id'   => '22',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '0',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'All Type Events',
                    'action_id'   => '23',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '22',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Create Type Events',
                    'action_id'   => '24',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '22',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'User',
                    'action_id'   => '25',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '0',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'All User Admin',
                    'action_id'   => '26',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '25',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Create User Admin',
                    'action_id'   => '27',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '25',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'Tickets',
                    'action_id'   => '28',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '0',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ],[
                    'name_menu'   => 'All Tickets',
                    'action_id'   => '29',
                    'url'       => '/google',
                    'is_delete'    => '0',
                    'parent_id'  => '28',
                    'description' => 'good luck for you',
                    'created_at'   => DB::raw('now()'),
                    'updated_at'   => DB::raw('now()'),
                ]
               
            ]; 
            DB::table('menus')->insert($menus);
        }
    }
}
